### ISSUE TITLE
检测结果置信度很低的问题

### ISSUE THREAD

**Issue by Smoothing97** [DetectionTeamUCAS/NAS_FPN_Tensorflow#1]
@yangJirui @yangxue0827 向大佬求助，我的参数设置和训练有什么硬伤：
用nas=2，FPN_CHANNEL=256来训练DOTA_H，数据集为裁剪后的800大小的图片，随机抽取10428张，模型采用resnet50_v1d.
学习率设置如下：
IMGNUM_IN_DATASET = 10428
EPSILON = 1e-5
MOMENTUM = 0.9
BATCH_SIZE = 1
WARM_SETP = 4*IMGNUM_IN_DATASET
#make lr bigger
LR = 5e-3 * 2  * len(GPU_GROUP.strip().split(',')) * BATCH_SIZE
MAX_ITERATION = 20*SAVE_WEIGHTS_INTE
DECAY_STEP = [13*IMGNUM_IN_DATASET, 20*IMGNUM_IN_DATASET]  # 50000, 70000
MAX_ITERATION = 20*IMGNUM_IN_DATASET
anchor设置如下：
USE_CENTER_OFFSET = True
LEVLES = ['P2', 'P3', 'P4', 'P5', 'P6']
BASE_ANCHOR_SIZE_LIST = [16, 32, 64, 128, 256]
ANCHOR_STRIDE_LIST = [4, 8, 16, 32, 64]
ANCHOR_SCALES = [1.0]
ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 5., 1 / 4., 4., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
ROI_SCALE_FACTORS = [10., 10., 5.0, 5.0, 5.0]
ANCHOR_SCALE_FACTORS = None
FPN设置如下：
SHARE_HEADS = True
KERNEL_SIZE = 3
RPN_IOU_POSITIVE_THRESHOLD = 0.7
RPN_IOU_NEGATIVE_THRESHOLD = 0.3
TRAIN_RPN_CLOOBER_POSITIVES = False

RPN_MINIBATCH_SIZE = 256
RPN_POSITIVE_RATE = 0.5
RPN_NMS_IOU_THRESHOLD = 0.7
RPN_TOP_K_NMS_TRAIN = 12000
RPN_MAXIMUM_PROPOSAL_TARIN = 2000

RPN_TOP_K_NMS_TEST = 6000
RPN_MAXIMUM_PROPOSAL_TEST = 1000
NAS_FPN和fast rcnn设置如下：
--------------------------------------------NAS FPN config
NUM_FPN = 0
NUM_NAS_FPN = 2
USE_RELU = True
#FPN_CHANNEL = 384
FPN_CHANNEL = 256
-------------------------------------------Fast-RCNN config
ROI_SIZE = 14
ROI_POOL_KERNEL_SIZE = 2
USE_DROPOUT = False
KEEP_PROB = 1.0
SHOW_SCORE_THRSHOLD = 0.6  # only show in tensorboard
#R2CNN CONFIG
FAST_RCNN_NMS_IOU_THRESHOLD = 0.1  # 0.6
FAST_RCNN_NMS_MAX_BOXES_PER_CLASS = 150
FAST_RCNN_IOU_POSITIVE_THRESHOLD = 0.4
FAST_RCNN_IOU_NEGATIVE_THRESHOLD = 0.0   # 0.1 < IOU < 0.5 is negative
FAST_RCNN_MINIBATCH_SIZE = 256  # if is -1, that is train with OHEM
FAST_RCNN_POSITIVE_RATE = 0.35
ADD_GTBOXES_TO_TRAIN = True
USE_ATTENTION = False
在训练过程中查看tensorboard的输出，检测效果尚可。但是导出ckpt检测，15个类别检测结果的置信度都很低，加上显示检测结果的阈值以后就没有可以显示的结果了。
比如这是ship的检测结果：
P0484_0000_0000 0.046 563.9 113.7 784.6 328.9
P0484_0000_0000 0.046 563.9 433.7 784.6 648.9
P0484_0000_0000 0.032 666.6 26.5 776.4 127.9
P0484_0000_0000 0.032 23.8 16.0 133.8 139.7
P0484_0000_0000 0.031 665.6 341.6 776.1 449.2
P0484_0000_0000 0.031 665.6 629.6 776.1 737.2
P0484_0000_0000 0.031 121.0 16.2 229.1 138.9
P0484_0000_0000 0.031 537.1 16.3 645.1 138.9
P0484_0000_0000 0.031 409.1 16.3 517.1 138.9
P0484_0000_0000 0.031 313.1 16.3 421.1 138.9
P0484_0000_0000 0.031 217.1 16.3 325.1 138.9
P0484_0000_0000 0.031 772.2 738.8 798.9 786.4
P0484_0000_0000 0.030 55.8 657.7 171.0 777.6
P0484_0000_0000 0.030 0.9 741.6 55.0 798.4
P0484_0000_0000 0.030 215.6 657.5 330.7 777.6
将显示检测框的阈值设置为0.03后，所有的框都是一个形状：
![image](https://user-images.githubusercontent.com/32809975/57963607-40ef8500-7959-11e9-8f72-828f471fbc40.png)
![image](https://user-images.githubusercontent.com/32809975/57963606-33d29600-7959-11e9-86b5-5b5d75ae0a72.png)

**Comment by Smoothing97** [comment]
在tensorboard里看训练到44460step输出的final_detection_img,感觉还可以？但是ckpt检测出来就很差，两者反差太大了，所以训练过程中输出的final_detection_img可以作为参考吗？
![image](https://user-images.githubusercontent.com/32809975/57963656-1b16b000-795a-11e9-979a-0446e8db4694.png)

**Comment by yangxue0827** [comment]
可能是你在测试的时候没有加载上训练好的权重，加载的是预训练的 @Smoothing97

**Comment by Smoothing97** [comment]
@yangxue0827 不，我特意输出了ckpt的路径，
checkpoint_path=============> /home/smoothing/NAS_FPN_Tensorflow-master/output/trained_weights/FPN_resnet50_v1d_DOTA_20190515_nas_2_Part5/dota_32302model.ckpt
model restore from : /home/smoothing/NAS_FPN_Tensorflow-master/output/trained_weights/FPN_resnet50_v1d_DOTA_20190515_nas_2_Part5/dota_32302model.ckpt

**Comment by Smoothing97** [comment]
我从55000张800大小的水平数据里随机抽了10000张，一个1poch是10000，学习率采用warmup_cosine，warm step我设置了前4个epoch，两块1080TI训练，所以在20000step的时候
![image](https://user-images.githubusercontent.com/32809975/57963955-3afca280-795f-11e9-982a-1a064a8904d5.png)
学习率warmup到了我设定的0.01*2。
让我头疼的是，如果我的权重没加载错（从输出的路径来看是的），用demo.py检测每一张图，都是一个样子的检测框，置信度还都很低....

**Comment by Smoothing97** [comment]
@yangxue0827 ：）打开在这个10000张随机水平800大小的DOTA数据训练了34000step的tensorboard文件，发现训练阶段显示的final_detection_img效果也不怎么样呢【手动微笑
![image](https://user-images.githubusercontent.com/32809975/57964017-6633c180-7960-11e9-9693-80a2a946ecad.png)
![image](https://user-images.githubusercontent.com/32809975/57964033-954a3300-7960-11e9-9690-e422a4aa40ee.png)
看了一下score_greater_05_rois....
![image](https://user-images.githubusercontent.com/32809975/57964043-d3475700-7960-11e9-864e-d135a6edec47.png)
![image](https://user-images.githubusercontent.com/32809975/57964052-f245e900-7960-11e9-959b-a76ee04f90ac.png)
嗯没看出什么来，所以又看了一下score_greater_09_rois....
![image](https://user-images.githubusercontent.com/32809975/57964060-1f929700-7961-11e9-8cf9-039e63f07360.png)
![image](https://user-images.githubusercontent.com/32809975/57964067-39cc7500-7961-11e9-80d0-33ebce2a9c9c.png)
ROI生成的这么清奇...按照算法里还要取score高的roi作为proposal_target_layer的输入...
fpn_box_pred这两个值应该是网络自己预测出来的，所以问题应该是在我设置的anchor参数有问题（吧？

**Comment by yangxue0827** [comment]
前期因为就加了wareup，所以你看前期tensorboard的效果不会那么好，需要多训练一会。另外建议你测一下训练集图片，如果没有结果那就是测试代码的问题了。 @Smoothing97
