### ISSUE TITLE
NAS+Cascade loss 无法下降

### ISSUE THREAD

**Issue by Arthur-Shi** [DetectionTeamUCAS/NAS_FPN_Tensorflow#11]
您好，

我这边将您的NAS和Cascade连在了一起，但是loss始终降不下来。

我的实际操作就是将nas_fpn.py 放入了cascade中，然后在那边的cascade的resnet.py稍微修改了一下。

但是loss始终在3, 降不下来， 请您给点建议指点，谢谢。

**Comment by yangxue0827** [comment]
你先训练下去，看看效果吧，这种原因我也不好判断，你可以把你QQ或者微信发我邮箱，我加你交流 @Arthur-Shi

**Comment by zhengze2014** [comment]
@yangxue0827 你好 我想问下你这个开源代码是用了NAS-FPN的网络构造拉提取特征 最后训练检测网络Faster-RCNN， 还是用NAS来探索最佳的FPN网络构造 对tensorflow不是很懂。。。对于我自己的数据想找到最合适的FPN网络。可是找不到源码，希望大神看到了多指点下
